apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sample-app
  labels:
    app: sample-app
spec:
  selector:
    app: sample-app
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8000
